### PR TITLE
Create compilation.yml

### PR DESCRIPTION
**Pull request by AKuHAK**
Tools and modules generation as artifacts and as releases

### CODE REVIEW

**Comment by frno7** [comment]
I'm considering making a proper Gentoo package for IOPMOD. Maybe we could have this package build both the tools and the IRX files, here then?

**Comment by AKuHAK** [comment]
CI is used not only for generating output files, but also for code debugging. So as much conditions tested, as better. Basically, it willbe not CI but CI/CD. Currently your makefile provides different targets for these 2 sections, so I decided to test them separately. This can make sense in the future when tools will be ported into other platforms, as we dont need to change modules part (modules are platform independent).
This is for testing more, binaries are more like aide effectof testing.

**Comment by frno7** [comment]
This is a good starting point. Merged in commit ba7c405870a0f0ab902d3046322bd53f0157277d. Thank you for your contribution, @AKuHAK!

**Comment by AKuHAK** [comment]
Doh, I made a typo...irx files arent populated into pre-release only in artifacts.

**Comment by AKuHAK** [comment]
also [this issue](https://github.com/frno7/iopmod/issues/6) can be closed now

**Comment by AKuHAK** [comment]
> Merged in commit [ba7c405](https://github.com/frno7/iopmod/commit/ba7c405870a0f0ab902d3046322bd53f0157277d).

It will be useful to propose these changes in other branches like `gamepad`.

**Comment by frno7** [comment]
> It will be useful to propose these changes in other branches like `gamepad`.

Yes, I’d be useful to have precompiled packages for experimental branches, such as the [`gamepad`](https://github.com/frno7/iopmod/tree/gamepad) branch, too.

**Pull request closed without merging**
